# Generated by Django 3.2.5 on 2021-07-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('title', models.TextField(max_length=250)),
                ('notes', models.TextField(max_length=500)),
                ('pickup_location', models.TextField(max_length=50)),
                ('dropoff_location', models.TextField(max_length=50)),
                ('date', models.DateField()),
                ('completed', models.BooleanField()),
            ],
        ),
    ]
